spring.application.name=demo

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=httpexchanges

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#spring.ai.mcp.server.stdio=true

# Log incoming/outgoing HTTP (headers + bodies)
#logging.level.org.zalando.logbook=TRACE
#
#logbook.format.style=http
#logbook.write.max-body-size=10240
#logbook.obfuscate.headers=Authorization,Cookie,Set-Cookie
#logbook.exclude=/actuator/**
#
## ensure request/response bodies can be read for logging
#spring.mvc.log-request-details=true
